/*  Message-number definitions derived from "ELWAFK.MSG"  */

#define AFKKEY      1
#define AFKSTR      3
#define TELAFK      4
#define TELNAM      5
#define AFKCOM      6
#define BAKCOM      7
#define CHGLOC      8
#define AFKLOC      9
#define SETBUSY    10
#define AFKALT     12
#define AFKHLP     13
#define YOURAFK    14
#define NOTON      15
#define NOAFK      16
#define WHO        17
#define AFKSET     18
#define TOLEAVE    19
